dist: trusty
sudo: false
language: python

python:
    - "2.7"
    - "3.6"
    - "pypy"
    - "pypy3"

addons:
    apt:
        packages:
            - gnupg2
            - tree
            - qrencode
            - xvfb
            - xclip
            - xz-utils
            - wget

before_install:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3 # give xvfb some time to start
    - mkdir base
    - export PATH="$PATH:$PWD/base/bin"
    - wget https://git.zx2c4.com/password-store/snapshot/password-store-master.tar.xz -O - | xzcat | tar xf -
    - cd password-store-master && make PREFIX=../base install && cd ..

install:
    - make PREFIX=base globalinstall
    - make install

script:
    - make headlesstest
