dist: trusty
sudo: false
language: python

python:
    - "2.7"
    - "3.6"
    - "pypy"
    - "pypy3"

addons:
    apt:
        packages:
            - git
            - gnupg2
            - tree
            - xclip
            - shellcheck

before_script:
    - git clone https://git.zx2c4.com/password-store
    - cd password-store && make PREFIX=/usr/local install

install:
    - make PREFIX=/usr/local globalinstall
    - make install

script:
    - shellcheck -s bash genphrase.bash
    - make test
