dist: bionic
language: python

python:
    - "2.7"
    - "3.5"
    - "3.6"
    - "3.7"
    - "3.8"
    - "pypy3"

services:
    - xvfb

addons:
    apt:
        packages:
            - gnupg2
            - tree
            - qrencode
            - xvfb
            - xclip
            - xz-utils
            - wget

before_install:
    - mkdir base
    - export PATH="$PATH:$PWD/base/bin"
    - wget https://git.zx2c4.com/password-store/snapshot/password-store-master.tar.xz -O - | xzcat | tar xf -
    - cd password-store-master && make PREFIX=../base install && cd ..

install:
    - make PREFIX=base globalinstall
    - make install

script:
    - make headlesstest
