dist: trusty
sudo: false
language: python

python:
    - "2.7"
    - "3.6"
    - "pypy"
    - "pypy3"

addons:
    apt:
        packages:
            - git
            - gnupg2
            - tree
            - xclip

before_install:
    - mkdir base
    - git clone https://git.zx2c4.com/password-store
    - cd password-store && make PREFIX=../base install

install:
    - make PREFIX=base globalinstall
    - make install

script:
    - make test
